server {
    listen 80;
    
    # Ativa compressão GZIP para deixar o site muito mais rápido
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # A mágica do React Router acontece aqui:
        try_files $uri $uri/ /index.html;
    }
}